[workspace]
resolver = "2"
members = [
  "encrypto-core",
  "encrypto-policy",
  "encrypto-pgp",
  "encrypto-cli"
]

[patch.crates-io]
sequoia-openpgp = { path = "vendor/sequoia-openpgp" }
ossl = { path = "vendor/ossl" }
